## YAML Template.
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: springbootadmin
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configuration
      failFast: true
      name: config-client
      profile: development
      username: admin
      password: qwerty
      retry:
        max-attempts: 1
        max-interval: 1000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS